### ISSUE TITLE
Why is working only IAP and NOT for Subscription ?

### ISSUE THREAD

**Issue by fcostantino** [NativeScript/payments#13]
This is the Kotlin code for retrieve the products info:
` SkuDetailsParams.newBuilder().setSkusList(skuList).setType(BillingClient.SkuType.SUBS).build() `

As you can see you need to setType SUBS/INAPP .

How do you handle this in your plugin?

Your exampe is working only on INAPP and fails on SUBS because return an empty List, native code works fine. 

Do you think that someone can fix this ?

**Comment by edusperoni** [comment]
We have specialized methods for subs:

https://github.com/NativeScript/payments/blob/main/packages/payments/index.d.ts#L18-L20

https://github.com/NativeScript/payments/blob/main/packages/payments/index.android.ts#L111-L117
