### ISSUE TITLE
No family sharing support

### ISSUE THREAD

**Issue by stumpykilo** [NativeScript/payments#23]
Please add support for family sharing for iOS, documentation found here:
https://developer.apple.com/documentation/storekit/skproduct/3564805-isfamilyshareable

I have made the changes locally but currently do not have access to create a PR, would someone be able to grant contributor access to me? @NathanWalker @bradmartin @edusperoni @Ombuweb 

Thanks.

**Comment by bradmartin** [comment]
@stumpykilo - You should be able to fork and make a PR to any public repo? Are you unable to do so, if so, maybe that's a new setting somewhere I'm not familiar with on github.

**Comment by stumpykilo** [comment]
@bradmartin my bad, I was reading the message incorrectly. PR created. Thank you!

**Comment by stumpykilo** [comment]
@bradmartin any idea on when this [PR](#24) might be reviewed?

**Comment by bradmartin** [comment]
I'll try to get to it shortly and publish an update. It looked okay if I recall, just forgot to circle back to it. Thanks for reminding me :)

**Comment by bradmartin** [comment]
Update published with PR merged today.

**Comment by stumpykilo** [comment]
@bradmartin I have tried the changes out and only part of Family Sharing works. I can now see what in-app purchases are family shareable but when restoring purchases the purchases for the family are not being restored. I do not see in Apple's documentation what else needs to be done according to this: https://developer.apple.com/documentation/storekit/in-app_purchase/original_api_for_in-app_purchase/supporting_family_sharing_in_your_app.

Any thoughts on how to proceed? Would you or your team be able to investigate further?

**Comment by stumpykilo** [comment]
It looks like it is not supported using TestFlight or Sandbox users: https://developer.apple.com/forums/thread/706205
