### ISSUE TITLE
Android Billing Library outdated starting November 1st 2023

### ISSUE THREAD

**Issue by MrSnoozles** [NativeScript/payments#26]
Starting November 2023 all app updates require Billing Library version 5 or newer.

https://developer.android.com/google/play/billing/deprecation-faq

`payments` is using version 4 at the moment.

**Comment by vivimdesign** [comment]
Any updates on this one?

**Comment by kprappbuilder** [comment]
Hello everyone, I have set about solving the problem, although this is not my job at all.  It cost me 4 days of work and nerves 😉 Otherwise I would have feared that my Nativescript Android app would have become unusable.  If you are interested in it, you can contact me.  (kprappbuilder@gmail.com) best regards

**Comment by brianrclow** [comment]
@kprappbuilder I was just about to start figuring out how to upgrade it as well from 4 -> 6. Are you interested in PR-ing your changes to the package? We could all benefit from that PR. If not, I'd be interested in figuring out how to get things upgraded and merged into this package.

**Comment by kprathome** [comment]
> @kprappbuilder I was just about to start figuring out how to upgrade it as well from 4 -> 6. Are you interested in PR-ing your changes to the package? We could all benefit from that PR. If not, I'd be interested in figuring out how to get things upgraded and merged into this package.

It really seems to work (test subscriptions/inapp purchases successful)
But I want to give the main developer of this plugin the opportunity to update it.
Therefore: If you are interested in advance, please feel free to contact me. (kprappbuilder@gmail.com)

**Comment by NathanWalker** [comment]
Thanks @MrSnoozles for tracking, we're working with @brianrclow to update it before the November deadline.

**Comment by rotibi** [comment]
From 1 August we cannot release apps with Play Billing library version 4.
![Screenshot from 2023-08-13 08-50-47](https://github.com/NativeScript/payments/assets/6384569/a8b76f8a-94ae-488d-804b-c38808a4ea79)
https://developer.android.com/google/play/billing/deprecation-faq

**Comment by kprathome** [comment]
I kindly offered a solution almost 2 months ago.  It works successfully in my app.  Instead of asking, this Nathan Walker flagged my offer as "abuse."  I would say very bad style, right?

**Comment by healerjoy** [comment]
@NathanWalker As this code has not been released [here](https://www.npmjs.com/package/@nativescript/payments) yet, can you please share the procedure to build this into a runnable nativescript plugin. Need to use it immediately in a live nativescript project.

Thank you for your help @NathanWalker.
